"""empty message

Revision ID: 9baa684781f9
Revises: ffdc0a98111c
Create Date: 2025-01-05 01:45:04.212593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9baa684781f9'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections_books', schema=None) as batch_op:
        batch_op.alter_column('collectionId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections_books', schema=None) as batch_op:
        batch_op.alter_column('collectionId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
